import javax.xml.parsers.*;

import java.io.File;
import java.util.List;


/**
 * Created by ejohns on 10/3/15.
 * This project was created to take in unclassified data created by reading the onr_icews_itrace.public.all_trace_with_event_summaries
 * and then transforming the data into the xml required by Orbis.  Currently it reads in a xml text file saved to a local HDD, but it can also be paired
 * with the database access code generated by Altova's mapforce.
 */

public class Processor {

    static String fileName = "//home/ejohns/Work/CINDE_DataTranslation/icews1.xml";
    static String directoryName = "/home/ejohns/Work/CINDE_DataTranslation/OrbisRecords/xmlRecords2/";
    static String writeLocation = "/home/ejohns/CIDNE_ORBIS_AFGHAN/";
    static Boolean isDirectory = false;
    static int writeIndex=0;
    public static void main(String[] args)
    {

            if (isDirectory) for (File file : getFiles(directoryName)) {
                processFile(file);
            }
            else
                processFile(new File(fileName));

        }



    public static File[] getFiles (String directory)

    {
        File[] files = new File(directory).listFiles();
        return files;

    }

    public static void processFile(File file)

    {


        try {
        SAXParserFactory factory =
                SAXParserFactory.newInstance();
        SummaryHandler Handler = new SummaryHandler(writeLocation);
        SAXParser saxParser = factory.newSAXParser();
        saxParser.parse(file, Handler);

        Handler.writeXML_file(writeLocation + writeIndex); //this is included so that any remaining data will be written out to disk

        }
        catch(Exception e){
            e.printStackTrace(System.err);
        }

    }




    }








