import javax.xml.parsers.*;

import java.io.File;



/**
 * Created by ejohns on 10/3/15.
 * This project was created to take in unclassified data created by reading the onr_icews_itrace.public.all_trace_with_event_summaries
 * and then transforming the data into the xml required by Orbis.  Currently it reads in a xml text file saved to a local HDD, but it can also be paired
 * with the database access code generated by Altova's mapforce.
 */

public class Processor {
    public static void main(String[] args) {
        String filename = "/home/ejohns/icews1.xml";
        String writeLocation = "/home/ejohns/xmlRecords2/";




            try {
                File inputFile = new File(filename);
                SAXParserFactory factory =
                        SAXParserFactory.newInstance();
                SummaryHandler Handler = new SummaryHandler(writeLocation);
                SAXParser saxParser = factory.newSAXParser();
                saxParser.parse(inputFile, Handler);

                Handler.writeXML_file(writeLocation); //this is included so that any remaining data will be written out to disk

                }
            catch (Exception e) {
                e.printStackTrace(System.err);
            }
    }






    }








